### ISSUE TITLE
Timestamp key passphrase not correctly set

### ISSUE THREAD

**Issue by radu-matei** [cnabio/signy#39]

**Comment by trishankatdatadog** [comment]
I will look into this

**Comment by trishankatdatadog** [comment]
I don't think there's anything to do here. The `timestamp` and `snapshot` are now pushed to Notary by default. Will double check.

**Comment by radu-matei** [comment]
Great!
Feel free to close the issue after you check.

Thanks!

**Comment by trishankatdatadog** [comment]
Both `timestamp` and `snapshot` pushed to Notary now.
