### ISSUE TITLE
Push verification image to a `cnabio` registry

### ISSUE THREAD

**Issue by radu-matei** [cnabio/signy#51]
The in-toto verification image currently used by Signy is linked to the old organization:

https://github.com/cnabio/signy/blob/21e031d2a8679af54b426d1d81070eb381e25cfc/cmd/verify.go#L78

We need to:

- put the Dockerfile for the verification image in the repository
- push the image to a well-known registry (ideally, consistent with how other projects in `cnabio` distribute container images).

**Comment by trishankatdatadog** [comment]
Right now, we are using `docker.io/trishankatdatadog/signy-in-toto-verifier` for our code and tests, which is not ideal.

**Comment by radu-matei** [comment]
Ideally, we would version the image together with Signy, and publish images whenever we release Signy.

For this, we should use the same registry we use for other container images, and have a GitHub action that publishes to the registry on release.

I think @vdice may have access to the credentials for the registry?

**Comment by vdice** [comment]
> I think @vdice may have access to the credentials for the registry?

Registry meaning `docker.io/cnabio`?  Yes, I can help add users and/or create a bot/new creds w/ access this org for CI.  Let me know.

**Comment by trishankatdatadog** [comment]
Can both of you help me push [here](https://github.com/cnabio/signy/pull/73/files#diff-e9f950f17198d3d5e3122a44230a09b9R31)?

**Comment by vdice** [comment]
@trishankatdatadog Please try re-running the action(s) when convenient.  Both secrets should now have values.

Note, if not already aware: `Secrets are not passed to workflows that are triggered by a pull request from a fork.`
