### ISSUE TITLE
Add `version` command

### ISSUE THREAD

**Issue by radu-matei** [cnabio/signy#60]
We need a simple `version` command that tells us the version and build date.

For an example of how to wire it up in the `Makefile`, here is the relevant part from `cnab-to-oci`:

https://github.com/cnabio/cnab-to-oci/blob/c91ac3daf0d74446a914727e80ffa15529da16d8/Makefile#L26-L29

**Comment by cvhariharan** [comment]
Hi, if this issue is still open, I can look into it

**Comment by trishankatdatadog** [comment]
Please do!
